version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependency-updates:
        applies-to: version-updates
        update-types:
        - major
        - minor
        - patch
      security-updates:
        applies-to: security-updates
        dependency-type: production
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependency-updates:
        applies-to: version-updates
        update-types:
        - major
        - minor
        - patch
      security-updates:
        applies-to: security-updates
        dependency-type: production
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
